{"name":"SetMeta: Failure","fullName":"TestSignContractRequestPgRepoSuiteRunner/SignContractRequestPgRepoSuite/TestSignContractRequestPgRepo_SetMetaFailure","status":"failed","statusDetails":{"message":"\tError:      \tTarget error should be in err chain:\n\t            \texpected: \"sql: connection is already closed\"\n\t            \tin chain: \"call to ExecQuery 'UPDATE requests SET meta=$1 WHERE request_id=$2' with args [{Name: Ordinal:1 Value:[123 34 110 105 99 107 110 97 109 101 34 58 34 108 101 99 108 101 114 99 34 44 34 100 101 115 99 114 105 112 116 105 111 110 34 58 34 84 101 115 116 32 100 101 115 99 114 105 112 116 105 111 110 34 125]} {Name: Ordinal:2 Value:123}], was not expected, next expectation is: ExpectedQuery =\u003e expecting Query, QueryContext or QueryRow which:\\n  - matches sql: 'UPDATE requests SET meta=$1 WHERE request_id=$2'\\n  - is with arguments:\\n    0 - [123 34 110 105 99 107 110 97 109 101 34 58 34 108 101 99 108 101 114 99 34 44 34 100 101 115 99 114 105 112 116 105 111 110 34 58 34 84 101 115 116 32 100 101 115 99 114 105 112 116 105 111 110 34 125]\\n    1 - 123\\n  - should return error: sql: connection is already closed\"\n","trace":"\n\n\tError Trace:\t/Users/rauzh/Desktop/cook_droogers/PPO_DB/cook-droogers/backend/vendor/github.com/ozontech/allure-go/pkg/framework/asserts_wrapper/wrapper/wrapper.go:243\n\t            \t\t\t\t/Users/rauzh/Desktop/cook_droogers/PPO_DB/cook-droogers/backend/vendor/github.com/ozontech/allure-go/pkg/framework/asserts_wrapper/wrapper/helper.go:37\n\t            \t\t\t\t/Users/rauzh/Desktop/cook_droogers/PPO_DB/cook-droogers/backend/vendor/github.com/ozontech/allure-go/pkg/framework/asserts_wrapper/wrapper/wrapper.go:239\n\t            \t\t\t\t/Users/rauzh/Desktop/cook_droogers/PPO_DB/cook-droogers/backend/vendor/github.com/ozontech/allure-go/pkg/framework/asserts_wrapper/helper/helper.go:67\n\t            \t\t\t\t/Users/rauzh/Desktop/cook_droogers/PPO_DB/cook-droogers/backend/internal/requests/sign_contract/repo/pg/sign_req_test.go:206\n\t            \t\t\t\t/Users/rauzh/Desktop/cook_droogers/PPO_DB/cook-droogers/backend/vendor/github.com/ozontech/allure-go/pkg/framework/core/common/steps.go:27\n\t            \t\t\t\t/Users/rauzh/Desktop/cook_droogers/PPO_DB/cook-droogers/backend/internal/requests/sign_contract/repo/pg/sign_req_test.go:185\n\tError:      \tTarget error should be in err chain:\n\t            \texpected: \"sql: connection is already closed\"\n\t            \tin chain: \"call to ExecQuery 'UPDATE requests SET meta=$1 WHERE request_id=$2' with args [{Name: Ordinal:1 Value:[123 34 110 105 99 107 110 97 109 101 34 58 34 108 101 99 108 101 114 99 34 44 34 100 101 115 99 114 105 112 116 105 111 110 34 58 34 84 101 115 116 32 100 101 115 99 114 105 112 116 105 111 110 34 125]} {Name: Ordinal:2 Value:123}], was not expected, next expectation is: ExpectedQuery =\u003e expecting Query, QueryContext or QueryRow which:\\n  - matches sql: 'UPDATE requests SET meta=$1 WHERE request_id=$2'\\n  - is with arguments:\\n    0 - [123 34 110 105 99 107 110 97 109 101 34 58 34 108 101 99 108 101 114 99 34 44 34 100 101 115 99 114 105 112 116 105 111 110 34 58 34 84 101 115 116 32 100 101 115 99 114 105 112 116 105 111 110 34 125]\\n    1 - 123\\n  - should return error: sql: connection is already closed\"\n\tTest:       \tSetMeta: Failure\n"},"start":1727635829906,"stop":1727635829906,"uuid":"b2ee6afa-7e93-11ef-a65f-be2bab8c44a1","historyId":"b0168830e51e540fac92ad61219def42","testCaseId":"d1165e885073765029e25ba36b6179f8","labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"MacBook-Pro-Pavel-2.local"},{"name":"thread","value":"TestSignContractRequestPgRepoSuiteRunner/SignContractRequestPgRepoSuite/TestSignContractRequestPgRepo_SetMetaFailure"},{"name":"suite","value":"SignContractRequestPgRepoSuite"},{"name":"package","value":"cookdroogers/internal/requests/sign_contract/repo/pg"},{"name":"tag","value":"SignContractRequestPgRepo"}],"steps":[{"name":"Failure","status":"failed","start":1727635829906,"stop":1727635829906,"steps":[{"name":"ASSERT: Error Is","status":"failed","start":1727635829906,"stop":1727635829906,"parameters":[{"name":"Error","value":"call to ExecQuery 'UPDATE requests SET meta=$1 WHERE request_id=$2' with args [{Name: Ordinal:1 Value:[123 34 110 105 99 107 110 97 109 101 34 58 34 108 101 99 108 101 114 99 34 44 34 100 101 115 99 114 105 112 116 105 111 110 34 58 34 84 101 115 116 32 100 101 115 99 114 105 112 116 105 111 110 34 125]} {Name: Ordinal:2 Value:123}], was not expected, next expectation is: ExpectedQuery =\u003e expecting Query, QueryContext or QueryRow which:\n  - matches sql: 'UPDATE requests SET meta=$1 WHERE request_id=$2'\n  - is with arguments:\n    0 - [123 34 110 105 99 107 110 97 109 101 34 58 34 108 101 99 108 101 114 99 34 44 34 100 101 115 99 114 105 112 116 105 111 110 34 58 34 84 101 115 116 32 100 101 115 99 114 105 112 116 105 111 110 34 125]\n    1 - 123\n  - should return error: sql: connection is already closed"},{"name":"Target","value":"sql: connection is already closed"}]}]}]}